### ISSUE TITLE
System.ArgumentException: Synthesis.esp has too many masters on masters list

### ISSUE THREAD

**Issue by nwn9** [SteveTownsend/BDSv2Patcher#15]
https://pastebin.com/ca7mZJtx

**Comment by SteveTownsend** [comment]
you have to split your patch into more than one when this happens. e.g. partition the patchers into those that edit CELL, those that edit WEAP/ARMO, and so on. Generate each and after each subset, rename Synthesis.esp to something else for inclusion in your LO.

I already had to do this myself. Synthesis has no automation for this case.
